name: cportal_flutter
description: Crossplatform corparative portal.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Dependency Injection tool
  get_it: ^7.2.0

  # Remote API
  dio: ^4.0.5
  internet_connection_checker: ^0.0.1+3

  # Functional programming things
  dartz: ^0.10.1

  # Value equality
  equatable: ^2.0.3

  # Key-value local cache/db
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13

  # Firebase services
  # firebase_core: ^1.13.1
  # firebase_messaging: ^11.2.11

  # Localization
  intl: ^0.17.0

  # Theme
  adaptive_theme: ^2.3.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  pinput: ^2.2.7
  pixel_perfect: ^1.1.1
  flutter_screenutil: ^5.3.1

  # State management for realisation bisness logic
  bloc_concurrency: ^0.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # Other
  device_info_plus_web: ^2.1.0
  go_router: ^3.0.7
  local_auth: ^1.1.11
  flutter_dotenv: ^5.0.2

  # flutter_web_auth: ^0.4.1

dev_dependencies:
  dart_code_metrics: ^4.13.0
  flutter_lints: ^1.0.0
  l: ^3.2.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/img/
    - assets/icons/navbar/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
