name: cportal_flutter
description: Crossplatform corparative portal.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Dependency Injection tool
  get_it: ^7.2.0

  # Remote API
  dio: ^4.0.6
  internet_connection_checker: ^0.0.1+3

  # Functional programming things
  dartz: ^0.10.1

  # Value equality
  equatable: ^2.0.3

  # Key-value local cache/db
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13

  # Localization
  intl: ^0.17.0

  # Theme
  adaptive_theme: ^2.3.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  pinput: ^2.2.9
  pixel_perfect: ^1.1.1

  # State management for realisation bisness logic
  bloc_concurrency: ^0.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # Other
  device_info_plus_web: ^2.1.0
  go_router: ^3.1.0
  local_auth: ^1.1.11
  flutter_dotenv: ^5.0.2
  swipe: ^0.0.1
  fluttertoast: ^8.0.9
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  camera: ^0.9.5+1
  flutter_vibrate: ^1.3.0

  # flutter_web_auth: ^0.4.1

  # Image Cache package
  extended_image: ^6.1.0
  responsive_framework: ^0.1.8
  qr_flutter: ^4.0.0
  bloc_test: ^9.0.3
  retrofit: ^3.0.1+1
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  device_info_plus: ^4.0.0

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_lints: ^1.0.0
  l: ^3.2.0
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.8
  # Testing packages
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  mocktail: ^0.3.0
  test: ^1.19.5
  retrofit_generator: ^4.0.1

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/img/
    - assets/img/onboarding/
    - assets/icons/navbar/
    - assets/icons/profile/

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
