name: Build Flutter APK

on:
  push:
    branches: ["dev"]
    tags:
      - "v1.0.${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --flavor=dev --split-per-abi

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
